### PR TITLE
FoldM variations of scanners

### PR DESCRIPTION
**Pull request by bens**
The scanner functionality is great but I think complicated folds could be easier to write with a monad mixed in, like State.

### CODE REVIEW

**Comment by mrkkrp** [comment]
The build is failing because of missing docs. If you're feeling lazy I can merge it as is and add the docs myself later.

**Comment by mrkkrp** [comment]
Another problem with this is that `Fold` and `FoldM` cannot be mixed together in one scan, which defeats the original purpose of all this stuff. I'll need to think more about this.

**Comment by bens** [comment]
There are the `generalize` and `simplify` functions in the `foldl` library, that would allow them to be combined.

**Comment by mrkkrp** [comment]
Oh, that's great. My usage of the library always was around the simple `Fold` type, so I missed those.

**Comment by bens** [comment]
I've added some haddock strings, if they're satisfactory I'm happy for you to merge it.  Cheers!

**Comment by mrkkrp** [comment]
LGTM, thanks!

**Pull request merged**
